config/routes.rb
Rails.application.routes.draw do
  resources :vendor_sweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :sweets, only: [:index, :show]
  resources :vendors
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sweet.rb
class Sweet < ApplicationRecord
  belongs_to :vendor
end

app/models/vender_sweet.rb
class VenderSweet < ApplicationRecord
  belongs_to :sweets
  belongs_to :vendors

  validates :price, presence: true
  
end

app/models/vendor.rb
class Vendor < ApplicationRecord
    has_many :vendor_sweets
    has_many :sweets, through: :vendor_sweets
end

app/models/vendor_sweet.rb
class VendorSweet < ApplicationRecord
  belongs_to :vendor
  belongs_to :sweet

  validates :price, presence: true
  validates :price, numericality: { only_integer: true }
  validates :price, numericality: { less_than: 0}
end

app/models/vendorsweet.rb
class Vendorsweet < ApplicationRecord
belongs_to :vendor
belongs_to :sweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  before_action :find_sweet, only: [:show]
  
  def index
    @sweets = Sweet.all
  end

  def show

  end

  private
  def find_sweet
    @sweet = Sweet.find(params[:id])
  end
end

app/controllers/vender_sweets_controller.rb
class VenderSweetsController < ApplicationController
  

  def index
    @vendor_sweets = VenderSweet.all
  end

  def show
    @vendor_sweet = VenderSweet.find(params[:id])
  end
  
  def new
    @vendor_sweet = VenderSweet.new
  end

  def create
    @vendor_sweet = VenderSweet.create(vender_params)
    redirect_to @vendor_sweet
    # if @vendor_sweet.valid?
    #   redirect_to @vendor_sweet
    # else
    #   flash[:errors] = @vendor_sweet.errors.full_messages
    #   redirect_to new_vender_sweet_path
    # end
  end

  private

    # def find_vender_sweet
    #   @vendor_sweet = VenderSweet.find(params[:id])
    # end

    def vender_params
      params.require(:vender_sweet).permit(:price, :vendors, :sweets)
    end

end

app/controllers/vendor_sweets_controller.rb
class VendorSweetsController < ApplicationController

  def index
    @vendor_sweets = VendorSweet.all
  end

  def show
    get_vendor_sweet
  end

  def new
    @vendor_sweet = VendorSweet.new
  end

  def create
    @vendor_sweet = VendorSweet.new(vendor_sweet_params)
    if @vendor_sweet.valid?
      redirect_to @vendor_sweet
    else
      render :new
    end
  end

private

def vendor_sweet_params
  params.require(:vendor_sweet).permit(:vendor_id, :sweet_id, :price)
end

def get_vendor_sweet
  @vendor_sweet = VendorSweet.find(params[:id])
end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :find_vendor, only: [:show]

  def index
    @vendors = Vendor.all
  end

  def show
    @vendor_sweets = @vendor.vendor_sweets
  end


  private
  def find_vendor
    @vendor = Vendor.find(params[:id])
  end

end

app/controllers/vendorsweets_controller.rb
class VendorsweetsController < ApplicationController
    def index
        @vendorsweets = Vendorsweets.all
    end 

    def show 
        @vendorsweet = Vendorsweet.find(params[:id])
    end 

    def new
        @vendorsweet = Vendorsweet.new
    end

    def create
     @vendorsweet = Vendorsweet.create(vendorsweet_params)

      redirect_to vendorsweet_path(@vendorsweet)
    end 
end

private

    def vendorsweet_params
        params.require(:vendorsweet).permit(:vendor_id, :sweet_id, :price)
    end3

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/helpers/vender_sweets_helper.rb
module VenderSweetsHelper
end

app/helpers/vendor_sweets_helper.rb
module VendorSweetsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/vendorsweets_helper.rb
module VendorsweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sweets/create.html.erb
<h1>Sweets#create</h1>
<p>Find me in app/views/sweets/create.html.erb</p>

app/views/sweets/destroy.html.erb
<h1>Sweets#destroy</h1>
<p>Find me in app/views/sweets/destroy.html.erb</p>

app/views/sweets/edit.html.erb
<h1>Sweets#edit</h1>
<p>Find me in app/views/sweets/edit.html.erb</p>

app/views/sweets/index.html.erb
<h1>All Sweets</h1>
<hr>

<ul>
  <% @sweets.each do |sweet| %>
    <li><%= link_to sweet.name, sweet_path(sweet) %></li>
  <% end  %>
</ul>

app/views/sweets/new.html.erb
<h1>Sweets#new</h1>
<p>Find me in app/views/sweets/new.html.erb</p>

app/views/sweets/show.html.erb
<h1><%= @sweet.name %><h1>

app/views/sweets/update.html.erb
<h1>Sweets#update</h1>
<p>Find me in app/views/sweets/update.html.erb</p>

app/views/vender_sweets/index.html.erb
<h1> VendorSweet Index <h1>

<h3><%= link_to "Create A New Vendor", new_vender_sweet_path %></h3>

app/views/vender_sweets/new.html.erb
<h1> Create A VendorSweet </h1>

<%= form_for @vendor_sweet do |f| %>
  <%= f.label :vendors %>
  <%= f.collection_select :vendors_id, Vendor.all, :id, :name %>
  <%= f.label :sweets %>
  <%= f.collection_select :sweets_id, Sweet.all, :id, :name %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.submit %>
<% end %>

app/views/vender_sweets/show.html.erb
<h1> Vendor </h1>

app/views/vendor_sweets/_form.html.erb
<%= form_for @vendorsweet do |v| %>

<%= v.label :price %>
<%= v.number_field :price %>
<%= v.label :vendor %>
<%= v.collection_select :vendor_id, @vendors, :id, :name%>
<%= v.label :sweet %>
<%= v.collection_select :sweet_id, @sweets, :id, :name%>
<%= v.submit %>
<% end %>

app/views/vendor_sweets/create.html.erb
<h1>Vendorsweets#create</h1>
<p>Find me in app/views/vendorsweets/create.html.erb</p>

app/views/vendor_sweets/destroy.html.erb
<h1>Vendorsweets#destroy</h1>
<p>Find me in app/views/vendorsweets/destroy.html.erb</p>

app/views/vendor_sweets/edit.html.erb
<h1>Vendorsweets#edit</h1>
<p>Find me in app/views/vendorsweets/edit.html.erb</p>

app/views/vendor_sweets/index.html.erb
<h1>All Purchases</h1>

<ul>
  <% @vendor_sweets.each do |purchace| %>
    <li><%= link_to purchace.sweet.name, purchace %></li>
  <% end  %>
</ul>

app/views/vendor_sweets/new.html.erb
<h1>Create a new pair</h1>


<%= form_for @vendor_sweets do |f| %>
  <%= f.label :name %><br>
  <%= f.collection_select :vendor_id, @vendors, :id, :name %><br>
  <%= f.label :name %><br>
  <%= f.collection_select :sweet_id, @sweets, :id, :name %><br>
  <%= f.label "Price" %><br>
  <%= f.integer :price %><br>
  <%= f.submit %>
<% end %>


<%= link_to "Check this Vendor", vendor_path(@vendor) %>

app/views/vendor_sweets/show.html.erb
<h2>
 <%= @vendor_sweet.vendor.name %>
</h2>

<ul>
  <% @sweets.each do |s| %>
     <li> <%= s.name %> </li>
   <% end %>
</ul>

app/views/vendor_sweets/update.html.erb
<h1>Vendorsweets#update</h1>
<p>Find me in app/views/vendorsweets/update.html.erb</p>

app/views/vendors/create.html.erb
<h1>Vendors#create</h1>
<p>Find me in app/views/vendors/create.html.erb</p>

app/views/vendors/destroy.html.erb
<h1>Vendors#destroy</h1>
<p>Find me in app/views/vendors/destroy.html.erb</p>

app/views/vendors/edit.html.erb
<h1>Vendors#edit</h1>
<p>Find me in app/views/vendors/edit.html.erb</p>

app/views/vendors/index.html.erb
<h1>All Vendors</h1>

<ul>
  <% @vendors.each do |vendor| %>

    <li><%= link_to vendor.name, vendor_path(vendor) %></li>
  <% end  %>
</ul>

app/views/vendors/new.html.erb
<h1>Vendors#new</h1>
<p>Find me in app/views/vendors/new.html.erb</p>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>

<ul>
    <% @vendor_sweets.each do | sweet | %>
        
            <li><%= sweet_id %></li><br>
    <% end %>
</ul>

app/views/vendors/update.html.erb
<h1>Vendors#update</h1>
<p>Find me in app/views/vendors/update.html.erb</p>

app/views/vendorsweets/index.html.erb
<h1>All Joiners</h1>

<ul>
  <% @vendorsweets.each do |joiner| %>
    <li><%= link_to joiner.price, @joiner %></li>
  <% end  %>
</ul>

app/views/vendorsweets/new.html.erb
<h1> Vendorsweets <h1>
<%= form_for @vendorsweet do |vs| %>
    <%= vs.label :price %>
    <%= vs.label :price %>
    <!--<%= vs.collection_select :vendor_id, @vendor, :id, :name%>-->
<%end%>

app/views/vendorsweets/show.html.erb

<h3>VendorSweet Details !!</h3>

<p><%= @vendorsweet.price %></p>


app/views/verdorsweets/new.html.erb
<h1>Create a VendorSweet</h1>

<%if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |err_message|%>
            <%= err_message %>
        <%end%>
    </ul>
<%end%>

<%=for_for @vendorsweet do |f|%>
    <%=f.label :price%>
    <%=f.number_field :price%>
    <%=f.label :vendor_id%>
    <%=f.collection_select :vendor_id, @vendors, :id, :name%>
    <%=f.label :sweet_id%>
    <%=f.collection_select :sweet_id, @sweets, :id, :name%>
    <%=f.submit "Sumbit"%>
<%end%>